############################
# STEP 1 build executable binary
############################
FROM golang:1.13.4-alpine AS builder
RUN apk update && apk add --no-cache git
WORKDIR /test
COPY . .
RUN go build -o /go/bin/test ./cmd/test
############################
# STEP 2 execute a small image
############################
FROM scratch
COPY --from=builder /go/bin/test /test
#TODO: fix as you like
EXPOSE 3000
ENTRYPOINT ["/test"]